name: scavis
description: Scavis
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  webview_flutter: ^2.0.8
  fluttertoast: ^8.0.7
  numberpicker: ^2.0.1
  path_provider: ^2.0.1
  #hive: ^1.4.4+1
  syncfusion_flutter_charts: ^19.1.55+1 
  syncfusion_flutter_gauges: ^19.1.55
  hexcolor: ^1.0.6
  font_awesome_flutter: ^9.0.0
  badges: ^1.2.0
  connectivity: ^3.0.3
  dio: ^4.0.0
  couchbase_lite: ^2.8.1
  url_launcher: ^6.0.3

  device_info_plus: ^0.7.2


  # Notifications and Alarm Clock
  flutter_local_notifications: ^3.0.1
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.9.0"
  # process icon with the following command in the terminal
  # flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/questionnaires/images/