import 'package:scavis/survey/components/questionnaire/types/questionnaire-question.dart';
import 'package:scavis/survey/components/questionnaire/template/questionnaire-template.dart';

class ZeitgeberQuestionnaire extends QuestionnaireTemplate {
  @override
  String id = "13_CB_Zeitgeber";

  @override
  String introduction = "Sogenannte “Zeitgeber” strukturieren unseren Alltag und wir nutzen sie oft, ohne uns dessen bewusst zu sein. Wie sieht das bei Ihnen aus?";
  
  @override
  List<QuestionnaireQuestion> questions = [
    QuestionnaireQuestion(questionId: "zeitgeber_1", text: "Ich trage meistens eine Armbanduhr.", type: AnswerFieldType.RADIOGROUP, answerOptions: [
      AnswerOption(label: "Ja, eine analoge Armbanduhr", value: 1),
      AnswerOption(label: "Ja, eine digitale Armbanduhr", value: 2),
      AnswerOption(label: "Ja, eine Smartwatch", value: 3),
      AnswerOption(label: "Nein", value: 4),
    ], options: {
      "radioImages": [
        "assets/questionnaires/images/watch-1.jpg",
        "assets/questionnaires/images/watch-2.jpg",
        "assets/questionnaires/images/watch-3.jpg",
        "assets/questionnaires/images/watch-4.jpg",
      ]
    }),
    QuestionnaireQuestion(questionId: "zeitgeber_2", text: "Ich nutze einen „echten“ Wecker zum Wecken, anstatt mein Mobiltelefon / Smartphone dafür zu verwenden.", type: AnswerFieldType.RADIOGROUP, answerOptions: [
      AnswerOption(label: "Ja", value: 1),
      AnswerOption(label: "Nein", value: 0),
    ]),
    QuestionnaireQuestion(questionId: "zeitgeber_3", text: "Ich nehme mein Mobiltelefon / Smartphone mit in mein Schlafzimmer.", type: AnswerFieldType.RADIOGROUP, answerOptions: [
      AnswerOption(label: "Ja", value: 1),
      AnswerOption(label: "Nein", value: 0),
    ]),
    QuestionnaireQuestion(questionId: "zeitgeber_4", text: "Ich lasse mich morgens durch mein Mobiltelefon / Smartphone wecken.", type: AnswerFieldType.RADIOGROUP, answerOptions: [
      AnswerOption(label: "Ja", value: 1),
      AnswerOption(label: "Nein", value: 0),
    ]),
    QuestionnaireQuestion(
        questionId: "zeitgeber_5",
        text: "Wie häufig wollen Sie „nur“ die Uhrzeit auf dem Mobiltelefon / Smartphone nachschauen und bleiben danach trotzdem unbeabsichtigt länger am Gerät als ursprünglich geplant (z.B. zum Checken von E-Mails)?",
        type: AnswerFieldType.RADIOGROUP,
        answerOptions: [
          AnswerOption(label: "Niemals", value: 1),
          AnswerOption(label: "Selten", value: 2),
          AnswerOption(label: "Manchmal", value: 3),
          AnswerOption(label: "Häufig", value: 4),
          AnswerOption(label: "Sehr häufig", value: 5),
        ]),
    QuestionnaireQuestion(
      questionId: "zeitgeber_6",
      text: "Wie schnell nach dem Aufwachen nehmen Sie üblicherweise morgens Ihr Mobiltelefon / Smartphone zum ersten Mal in die Hand und gehen online?",
      type: AnswerFieldType.SELECTION_SLIDER,
      answerOptions: [
        AnswerOption(label: "0 Minuten", value: 0),
        AnswerOption(label: "1 Minute", value: 1),
        AnswerOption(label: "2 Minuten", value: 2),
        AnswerOption(label: "3 Minuten", value: 3),
        AnswerOption(label: "4 Minuten", value: 4),
        AnswerOption(label: "5 Minuten", value: 5),
        AnswerOption(label: "6 Minuten", value: 6),
        AnswerOption(label: "7 Minuten", value: 7),
        AnswerOption(label: "8 Minuten", value: 8),
        AnswerOption(label: "9 Minuten", value: 9),
        AnswerOption(label: "10 Minuten", value: 10),
        AnswerOption(label: "11 Minuten", value: 11),
        AnswerOption(label: "12 Minuten", value: 12),
        AnswerOption(label: "13 Minuten", value: 13),
        AnswerOption(label: "14 Minuten", value: 14),
        AnswerOption(label: "15 Minuten", value: 15),
        AnswerOption(label: "16 Minuten", value: 16),
        AnswerOption(label: "17 Minuten", value: 17),
        AnswerOption(label: "18 Minuten", value: 18),
        AnswerOption(label: "19 Minuten", value: 19),
        AnswerOption(label: "20 Minuten", value: 20),
        AnswerOption(label: "21 Minuten", value: 21),
        AnswerOption(label: "22 Minuten", value: 22),
        AnswerOption(label: "23 Minuten", value: 23),
        AnswerOption(label: "24 Minuten", value: 24),
        AnswerOption(label: "25 Minuten", value: 25),
        AnswerOption(label: "26 Minuten", value: 26),
        AnswerOption(label: "27 Minuten", value: 27),
        AnswerOption(label: "28 Minuten", value: 28),
        AnswerOption(label: "29 Minuten", value: 29),
        AnswerOption(label: "30 Minuten", value: 30),
        AnswerOption(label: "31 Minuten", value: 31),
        AnswerOption(label: "32 Minuten", value: 32),
        AnswerOption(label: "33 Minuten", value: 33),
        AnswerOption(label: "34 Minuten", value: 34),
        AnswerOption(label: "35 Minuten", value: 35),
        AnswerOption(label: "36 Minuten", value: 36),
        AnswerOption(label: "37 Minuten", value: 37),
        AnswerOption(label: "38 Minuten", value: 38),
        AnswerOption(label: "39 Minuten", value: 39),
        AnswerOption(label: "40 Minuten", value: 40),
        AnswerOption(label: "41 Minuten", value: 41),
        AnswerOption(label: "42 Minuten", value: 42),
        AnswerOption(label: "43 Minuten", value: 43),
        AnswerOption(label: "44 Minuten", value: 44),
        AnswerOption(label: "45 Minuten", value: 45),
        AnswerOption(label: "46 Minuten", value: 46),
        AnswerOption(label: "47 Minuten", value: 47),
        AnswerOption(label: "48 Minuten", value: 48),
        AnswerOption(label: "49 Minuten", value: 49),
        AnswerOption(label: "50 Minuten", value: 50),
        AnswerOption(label: "51 Minuten", value: 51),
        AnswerOption(label: "52 Minuten", value: 52),
        AnswerOption(label: "53 Minuten", value: 53),
        AnswerOption(label: "54 Minuten", value: 54),
        AnswerOption(label: "55 Minuten", value: 55),
        AnswerOption(label: "56 Minuten", value: 56),
        AnswerOption(label: "57 Minuten", value: 57),
        AnswerOption(label: "58 Minuten", value: 58),
        AnswerOption(label: "59 Minuten", value: 59),
        AnswerOption(label: "60 Minuten", value: 60),
        AnswerOption(label: "Mehr als 60 Minuten", value: 9990),
      ],
    ),
    QuestionnaireQuestion(
      questionId: "zeitgeber_7",
      text: "Wie kurz vor dem Schlafengehen nehmen Sie üblicherweise Ihr Mobiltelefon / Smartphone zum letzten Mal in die Hand, um online zu gehen?",
      type: AnswerFieldType.SELECTION_SLIDER,
      answerOptions: [
        AnswerOption(label: "0 Minuten", value: 0),
        AnswerOption(label: "1 Minute", value: 1),
        AnswerOption(label: "2 Minuten", value: 2),
        AnswerOption(label: "3 Minuten", value: 3),
        AnswerOption(label: "4 Minuten", value: 4),
        AnswerOption(label: "5 Minuten", value: 5),
        AnswerOption(label: "6 Minuten", value: 6),
        AnswerOption(label: "7 Minuten", value: 7),
        AnswerOption(label: "8 Minuten", value: 8),
        AnswerOption(label: "9 Minuten", value: 9),
        AnswerOption(label: "10 Minuten", value: 10),
        AnswerOption(label: "11 Minuten", value: 11),
        AnswerOption(label: "12 Minuten", value: 12),
        AnswerOption(label: "13 Minuten", value: 13),
        AnswerOption(label: "14 Minuten", value: 14),
        AnswerOption(label: "15 Minuten", value: 15),
        AnswerOption(label: "16 Minuten", value: 16),
        AnswerOption(label: "17 Minuten", value: 17),
        AnswerOption(label: "18 Minuten", value: 18),
        AnswerOption(label: "19 Minuten", value: 19),
        AnswerOption(label: "20 Minuten", value: 20),
        AnswerOption(label: "21 Minuten", value: 21),
        AnswerOption(label: "22 Minuten", value: 22),
        AnswerOption(label: "23 Minuten", value: 23),
        AnswerOption(label: "24 Minuten", value: 24),
        AnswerOption(label: "25 Minuten", value: 25),
        AnswerOption(label: "26 Minuten", value: 26),
        AnswerOption(label: "27 Minuten", value: 27),
        AnswerOption(label: "28 Minuten", value: 28),
        AnswerOption(label: "29 Minuten", value: 29),
        AnswerOption(label: "30 Minuten", value: 30),
        AnswerOption(label: "31 Minuten", value: 31),
        AnswerOption(label: "32 Minuten", value: 32),
        AnswerOption(label: "33 Minuten", value: 33),
        AnswerOption(label: "34 Minuten", value: 34),
        AnswerOption(label: "35 Minuten", value: 35),
        AnswerOption(label: "36 Minuten", value: 36),
        AnswerOption(label: "37 Minuten", value: 37),
        AnswerOption(label: "38 Minuten", value: 38),
        AnswerOption(label: "39 Minuten", value: 39),
        AnswerOption(label: "40 Minuten", value: 40),
        AnswerOption(label: "41 Minuten", value: 41),
        AnswerOption(label: "42 Minuten", value: 42),
        AnswerOption(label: "43 Minuten", value: 43),
        AnswerOption(label: "44 Minuten", value: 44),
        AnswerOption(label: "45 Minuten", value: 45),
        AnswerOption(label: "46 Minuten", value: 46),
        AnswerOption(label: "47 Minuten", value: 47),
        AnswerOption(label: "48 Minuten", value: 48),
        AnswerOption(label: "49 Minuten", value: 49),
        AnswerOption(label: "50 Minuten", value: 50),
        AnswerOption(label: "51 Minuten", value: 51),
        AnswerOption(label: "52 Minuten", value: 52),
        AnswerOption(label: "53 Minuten", value: 53),
        AnswerOption(label: "54 Minuten", value: 54),
        AnswerOption(label: "55 Minuten", value: 55),
        AnswerOption(label: "56 Minuten", value: 56),
        AnswerOption(label: "57 Minuten", value: 57),
        AnswerOption(label: "58 Minuten", value: 58),
        AnswerOption(label: "59 Minuten", value: 59),
        AnswerOption(label: "60 Minuten", value: 60),
        AnswerOption(label: "Mehr als 60 Minuten", value: 9990),
      ],
    )
  ];
}
